"""
This type stub file was generated by pyright.
"""

def plot_all_placefields(active_placefields1D, active_placefields2D, active_config, variant_identifier_label=..., should_save_to_disk=..., **kwargs): # -> tuple[Any | None, Any | None, Any | None, Any]:
    """ Main function to plot all aspects of 1D and 2D placefields
    active_placefields1D: (Pf1D)
    active_placefields2D: (Pf2D)
    active_config:
    Usage:
        ax_pf_1D, occupancy_fig, active_pf_2D_figures = plot_all_placefields(active_epoch_placefields1D, active_epoch_placefields2D, active_config)
    """
    ...

def plot_placefield_occupancy(active_epoch_placefields, fig=..., ax=..., **kwargs): # -> tuple[Figure | Any, Axes | Any]:
    """ plots the placefield occupancy in a matplotlib figure. 
    Works for both 1D and 2D.
    
    from neuropy.plotting.placemaps import plot_placefield_occupancy
    
    """
    ...

