"""
This type stub file was generated by pyright.
"""

from ..core import ProbeGroup

def plot_probe(probe: ProbeGroup, annotate_channels=..., channel_id=..., disconnected=..., ax=...): # -> Any:
    ...

def plot_on_probe(probe: ProbeGroup): # -> None:
    ...

