"""
This type stub file was generated by pyright.
"""

from ..core import ProbeGroup

"""
This type stub file was generated by pyright.
"""
def plot_probe(probe: ProbeGroup, annotate_channels=..., channel_id=..., disconnected=..., ax=...):
    ...

def plot_on_probe(probe: ProbeGroup):
    ...

