"""
This type stub file was generated by pyright.
"""

from ..core import Signal

def plot_spectrogram(sxx, time, freq, freq_lim=..., ax=..., cmap=..., sigma=...): # -> Any:
    """Generating spectrogram plot for given channel

    Parameters
    ----------
    chan : [int], optional
        channel to plot, by default None and chooses a channel randomly
    period : [type], optional
        plot only for this duration in the session, by default None
    window : [float, seconds], optional
        window binning size for spectrogram, by default 10
    overlap : [float, seconds], optional
        overlap between windows, by default 2
    ax : [obj], optional
        if none generates a new figure, by default None
    """
    ...

def plot_signal_traces(signal: Signal, ax=..., pad=..., color=..., lw=...): # -> Any:
    ...

