"""
This type stub file was generated by pyright.
"""

class BinarysignalIO:
    def __init__(self, filename, dtype=..., n_channels=..., sampling_rate=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    
    @property
    def duration(self): # -> float:
        ...
    
    @property
    def n_frames(self): # -> int:
        ...
    
    def get_signal(self, channel_indx=..., t_start=..., t_stop=...): # -> Signal:
        ...
    
    def write_time_slice(self, write_filename, t_start, t_stop): # -> None:
        ...
    
    def __getstate__(self): # -> dict[str, Any]:
        """ Custom serialization/deserialization method to enable saving pipeline on macOS. Previously failed with the error:
            TypeError: cannot pickle 'mmap.mmap' object ' #11823
            Issue with macOS (Darwin) and multi-processing
            https://github.com/stamparm/maltrail/issues/11823
        """
        ...
    
    def __setstate__(self, state): # -> None:
        ...
    


