"""
This type stub file was generated by pyright.
"""

from ..core import Epoch

class SpykingCircusIO:
    def __init__(self) -> None:
        ...
    
    def load_rough_mua(self, mua_filename=...): # -> None:
        """Load in multi-unit activity (MUA) generated by running spyking-circus with the 'thresholding' flag.
        Note that this differs from MUA designated in phy after manual spike sorting (q = 6),
        so it is defined as Spikes.rough_mua"""
        ...
    
    def roughmua2neuroscope(self, chans, shankIDs): # -> None:
        """Exports all threshold crossings on electrodes entered to view in neuroscope to .clu.shankID and .res.shankID
        files for viewing in neuroscope.  Must run Spikes.load_mua first. Cluster ids correspond to electrodes.
        Chans = channel numbers in neuroscope."""
        ...
    
    @staticmethod
    def write_epochs(file, epochs: Epoch): # -> None:
        ...
    


