"""
This type stub file was generated by pyright.
"""

from ..ratemaps import enumTuningMap2DPlotMode, enumTuningMap2DPlotVariables

class RatemapPlottingMixin:
	def plot(self, computation_config=..., included_unit_indicies=..., subplots=..., figsize=..., fignum=..., enable_spike_overlay=..., spike_overlay_spikes=..., extended_overlay_points_datasource_dicts=..., drop_below_threshold: float = ..., plot_variable: enumTuningMap2DPlotVariables = ..., plot_mode: enumTuningMap2DPlotMode = ..., active_context=..., **kwargs): # -> tuple[Axes | Any, NDArray[Any] | NDArray[intp] | ndarray[Any, Any], ndarray[Any, Any]]:
		...
	


