"""
This type stub file was generated by pyright.
"""

def estimate_session_laps(sess, N=..., should_backup_extant_laps_obj=..., should_plot_laps_2d=..., time_variable_name=..., debug_plot=..., debug_print=...):
    """ 2021-12-21 - Pho's lap estimation from the position data (only)
    Replaces the sess.laps which is computed or loaded from the spikesII.mat spikes data (which isn't very good)

    CAVIAT: Only works for the linear track (not more complex environments/mazes)
    USES: Used in KDibaOldDataSessionFormat as a post-processing step to replace the laps computed from the spikesII.mat data

        2023-04-07 - Used in notebook to compute the laps if they aren't there so that we can filter by them.


    Note: Uses `sess.position`

    Uses: ['_subfn_perform_estimate_lap_splits_1D', 'Laps.from_estimated_laps', '_subfn_compute_laps_spike_indicies']
    
    
    debug_plot: if True, plots a user-customizable laps view with the points detected for each
    
    
    Updates:
        `sess.laps`

    """
    ...

def build_lap_computation_epochs(sess, use_direction_dependent_laps: bool = ...): # -> list[Any]:
    """ Builds desired_computation_epochs from the session's laps object

        from neuropy.analyses.laps import build_lap_computation_epochs

        desired_computation_epochs = build_lap_computation_epochs(global_session, use_direction_dependent_laps=True)
        desired_computation_epochs


    Notes:
        lap_specific_epochs.labels: ['0', '1', ..., '79'] == ['0', ..., f'{len(sess.laps.lap_id)-1}]

    """
    ...

