"""
This type stub file was generated by pyright.
"""

from .. import core

class ExplainedVariance(core.DataWriter):
    colors = ...
    def __init__(self, neurons: core.Neurons, template, matching, control, bin_size=..., window: int = ..., slideby: int = ..., pairs_bool=..., ignore_epochs: core.Epoch = ...) -> None:
        ...
    
    def plot(self, ax=..., t_start=..., legend=...): # -> Any:
        ...
    


class NeuronEnsembles(core.DataWriter):
    """[summary]

    Parameters
    ----------
    neurons : [type]
        [description]
    t_start : float
        start of the ensemble detection period
    t_stop : float
        end of the ensemble detection period
    bin_size : float
        bining for calculating spike counts
    frate_thresh : float
        exclude neurons with firing rate below or equal to this number
    ignore_epochs: core.Epoch

    References
    ----------
    1) van de Ven, G. M., Trouche, S., McNamara, C. G., Allen, K., & Dupret, D. (2016). Hippocampal offline reactivation consolidates recently formed cell assembly patterns during sharp wave-ripples. Neuron, 92(5), 968-974.Gido M. van de Ven et al. 2016
    """
    def __init__(self, neurons: core.Neurons, t_start=..., t_stop=..., bin_size=..., frate_thresh=..., ignore_epochs: core.Epoch = ...) -> None:
        ...
    
    def get_firing_rate_filter_mask(self):
        ...
    
    @staticmethod
    def get_firing_rate_filter(neurons, t_start, t_stop, frate_thresh):
        ...
    
    def get_original_data(self): # -> tuple[Any, NDArray[float64] | Any]:
        ...
    
    @property
    def n_ensembles(self): # -> Any:
        ...
    
    def calculate_activation(self, t_start=..., t_stop=..., bin_size=...): # -> None:
        ...
    
    def plot_activation(self, nrows=..., ncols=...): # -> None:
        ...
    
    def plot_ensembles(self, style=..., sort=...): # -> None:
        ...
    


