"""
This type stub file was generated by pyright.
"""

from .. import core

def detect_local_sleep_epochs(mua: core.Mua, ignore_epochs: core.Epoch = ...): # -> Epoch:
    """Detects local OFF events in within period

    Parameters
    ----------
    period : list,array-like
        period in seconds

    """
    ...

def detect_pbe_epochs(mua: core.Mua, thresh=..., min_dur=..., merge_dur=..., max_dur=...): # -> Epoch:
    """Detects putative population burst events

    Parameters
    ----------
    thresh : tuple, optional
        values based on zscore i.e, events with firing rate above thresh[0] and peak exceeding thresh[1], by default (0, 3) --> above mean and greater than 3 SD
    min_dur : float, optional
        minimum duration of a pop burst event, in seconds, default = 0.1 seconds
    merge_dur : float, optional
        if two events are less than this time apart, they are merged, in seconds
    max_dur : float, optional
        events only lasting below this duration
    """
    ...

def detect_lowstates_epochs(): # -> None:
    ...

