"""
This type stub file was generated by pyright.
"""

from neuropy.utils.mixins.dict_representable import DictRepresentable
from neuropy.utils.mixins.file_representable import FileRepresentable
from neuropy.utils.mixins.print_helpers import SimplePrintable

"""
This type stub file was generated by pyright.
"""
class LegacyDataLoadingMixin:
    @classmethod
    def legacy_from_dict(cls, dict_rep: dict):
        """ Tries to load the dict using previous versions of this code. """
        ...
    


class DataWriter(FileRepresentable, DictRepresentable, LegacyDataLoadingMixin, SimplePrintable):
    def __init__(self, metadata=...) -> None:
        ...
    
    @property
    def filename(self):
        ...
    
    @filename.setter
    def filename(self, f):
        ...
    
    @property
    def metadata(self):
        ...
    
    @metadata.setter
    def metadata(self, d):
        """metadata compatibility"""
        ...
    
    @staticmethod
    def from_dict(d):
        ...
    
    def to_dict(self, recurrsively=...):
        ...
    
    @classmethod
    def from_file(cls, f):
        ...
    
    @classmethod
    def to_file(cls, data: dict, f, status_print=...):
        ...
    
    def save(self, status_print=...):
        ...
    
    def delete_file(self):
        ...
    
    def create_backup(self):
        ...
    


