from pathlib import Path
from matplotlib import pyplot as plt
plt.rcParams["pdf.fonttype"] = 42
plt.rcParams["ps.fonttype"] = 42
import numpy as np
import pandas as pd
import scipy.io as sio

from neuropy.core import epoch
from neuropy.plotting.epochs import plot_hypnogram

# Dictionary below takes default SleepScoreMaster state names and maps them to default NeuroPy names
rename_dict = {"NREMstate": "nrem",
               "REMstate": "rem",
               "WAKEstate": "active",
               "Drowsystate": "quiet"}

class SleepScoreIO:
    """Class to read in .mat files generated by SleepScoreMaster and hand-edited using SleepScoreMaster
    fo assigning sleep states based on LFP and pseudo-EMG (derived from LFP) or externally recorded motion
    data.

    SleepScoreMaster is found at https://github.com/buzsakilab/buzcode in the 'detectors' folder and is built
    in MATLAB."""
    def __init__(self, basedir):
        self.basedir = Path(basedir)
        self.emg_params = None
    def read_emg(self):
        """Read in pseudo-EMG from SleepScoreMaster"""

        # Get file and check only one present
        emg_files = sorted(self.basedir.glob("*.EMGFromLFP.LFP.mat"))
        assert len(emg_files) == 1, f"1 EMG file expected, f{len(emg_files)} files found"
        emg_file = emg_files[0]

        # Read in file
        emg_dict = sio.loadmat(emg_file, simplify_cells=True)['EMGFromLFP']

        # Make into DataFrame
        emg_df = pd.DataFrame({"timestamps": emg_dict["timestamps"], "pEMG": emg_dict["data"]})

        # Save MetaData - Not working due to pd.DataFrame.attrs being experimental currently
        self.emg_params = {"channels": emg_dict["channels"], "SampleRate": emg_dict["samplingFrequency"],
                           "detectorName": emg_dict["detectorName"]}
        # emg_df.attrs = {"channels": emg_dict["channels"], "SampleRate": emg_dict["samplingFrequency"],
        #                 "detectorName": emg_dict["detectorName"]}

        return emg_df

    def read_states(self, rename_states: dict or None = rename_dict,
                    plot_states=True):
        files = sorted(self.basedir.glob("*.SleepState.states.mat"))

        assert len(files) == 1, f"1 state file expected, f{len(files)} files found"
        file = files[0]

        states_from_mat = sio.loadmat(file, simplify_cells=True)
        states_from_mat = states_from_mat['SleepState']['ints']
        all_epochs = []
        for matlab_label, epoch_times in states_from_mat.items():

            if epoch_times.size > 0 and epoch_times.ndim >= 2 and epoch_times.shape[1] >= 2:
                # Scale times to hours for better hypnogram display
                ep = epoch.Epoch.from_array(
                    starts=epoch_times[:, 0],
                    stops=epoch_times[:, 1],
                    labels=[matlab_label] * len(epoch_times)
                )
                all_epochs.append(ep)
        # Combine epochs
        if all_epochs:
            brainstates_epochs = all_epochs[0]
            for ep in all_epochs[1:]:
                brainstates_epochs += ep

        else:
            print('No epochs created')

        if rename_states is not None:
            for old_name, new_name in rename_dict.items():
                brainstates_epochs.rename_label(old_name, new_name)

        if plot_states:  # Plot hypnogram
            fig, ax = plt.subplots(figsize=(12, 4))
            plot_hypnogram(brainstates_epochs, ax=ax, annotate=True)  # Times already in hours, so use 's'
            plt.show()

        return brainstates_epochs

