"""
This type stub file was generated by pyright.
"""

class DiffableObject:
    """ Objects can be "diffed" to other objects of the same type or dictionaries, to see which members are the same and which differ. """
    def diff(self, other_object): # -> set[Any]:
        ...
    
    @staticmethod
    def compute_diff(lhs_dict, rhs_dict): # -> set[Any]:
        """Returns a set of the properties that have changed between the two objects. Objects should be dictionary or related types.

        Args:
            lhs ([type]): [description]
            rhs ([type]): [description]

        Returns:
            [type]: [description]
        """
        ...
    


